import { AuthContext, AuthProvider } from '@/contexts/AuthContext'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import GAnalytics from '@/components/GAnalytics'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <head>
          <script data-ad-client="pub-5931480780360258" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" >
          </script>
          {process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID && (
            <GAnalytics GA_MEASUREMENT_ID={process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID} />
          )}
        </head>
        <AuthProvider>
          <body className={inter.className}>{children}</body>
        </AuthProvider>
      </html>
  )
}
